// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbKQgLTkjYsVfdUZBO5PPJ9pSqicwwJgY',
    appId: '1:166350393893:web:a1b2c3d4e5f6g7h8i9j0k1l2',
    messagingSenderId: '166350393893',
    projectId: 'smart-parking-kalyan-2024',
    authDomain: 'smart-parking-kalyan-2024.firebaseapp.com',
    storageBucket: 'smart-parking-kalyan-2024.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbKQgLTkjYsVfdUZBO5PPJ9pSqicwwJgY',
    appId: '1:166350393893:android:62cb4150f69963412fe5cc',
    messagingSenderId: '166350393893',
    projectId: 'smart-parking-kalyan-2024',
    storageBucket: 'smart-parking-kalyan-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbKQgLTkjYsVfdUZBO5PPJ9pSqicwwJgY',
    appId: '1:166350393893:ios:b2c3d4e5f6g7h8i9j0k1l2m3',
    messagingSenderId: '166350393893',
    projectId: 'smart-parking-kalyan-2024',
    storageBucket: 'smart-parking-kalyan-2024.firebasestorage.app',
    iosBundleId: 'com.example.smartParkingAdminNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbKQgLTkjYsVfdUZBO5PPJ9pSqicwwJgY',
    appId: '1:166350393893:macos:c3d4e5f6g7h8i9j0k1l2m3n4',
    messagingSenderId: '166350393893',
    projectId: 'smart-parking-kalyan-2024',
    storageBucket: 'smart-parking-kalyan-2024.firebasestorage.app',
    iosBundleId: 'com.example.smartParkingAdminNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbKQgLTkjYsVfdUZBO5PPJ9pSqicwwJgY',
    appId: '1:166350393893:windows:d4e5f6g7h8i9j0k1l2m3n4o5',
    messagingSenderId: '166350393893',
    projectId: 'smart-parking-kalyan-2024',
    storageBucket: 'smart-parking-kalyan-2024.firebasestorage.app',
  );
}
