// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6sLPDh7hmfYTBa7EWZaQ9EYGsaEjyJ80',
    appId: '1:166350393893:web:5de9461d485ffd1d2fe5cc',
    messagingSenderId: '166350393893',
    projectId: 'smart-parking-kalyan-2024',
    authDomain: 'smart-parking-kalyan-2024.firebaseapp.com',
    storageBucket: 'smart-parking-kalyan-2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbKQgLTkjYsVfdUZBO5PPJ9pSqicwwJgY',
    appId: '1:166350393893:android:f666198a8b084c522fe5cc',
    messagingSenderId: '166350393893',
    projectId: 'smart-parking-kalyan-2024',
    storageBucket: 'smart-parking-kalyan-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBGr9li527Ib3xFMUhxm8w2g243EoSEy0',
    appId: '1:166350393893:ios:c47fb768738e40742fe5cc',
    messagingSenderId: '166350393893',
    projectId: 'smart-parking-kalyan-2024',
    storageBucket: 'smart-parking-kalyan-2024.firebasestorage.app',
    iosBundleId: 'com.example.smartParkingApp',
  );
}
